[advisories]
# Determine what happens when an unmaintained crate is found.
# Setting to none prevents CI from failing on things like Bincode which Solana uses but are "unmaintained"
unmaintained = "none"
# Determine what happens when a soundness issue is found.
unsound = "none"
# Determine what happens when a yanked crate is found.
yanked = "allow"
[bans]
# No bans configured
multiple-versions = "allow"
highlight = "all"
