// API Module
// HTTP API endpoints and handlers

pub mod address_only;
pub mod admin;
pub mod admin_routes;
pub mod analytics_handlers;
pub mod blog;
pub mod careers;
pub mod customer_handlers;
pub mod fee_breakdown;
pub mod merchant_auth_handlers;
pub mod merchant_handlers;
pub mod merchant_routes;
pub mod merchant_ws;
pub mod middleware;
pub mod notification_handlers;
pub mod p2p_auth_handlers;
pub mod p2p_handlers;
pub mod p2p_routes;
pub mod p2p_ws;
pub mod payment_handlers;
pub mod public_handlers;
pub mod public_routes;
pub mod routes;
pub mod security_monitoring;
pub mod settings_handlers;
pub mod state;
pub mod status;
pub mod wallet_management;
pub mod withdrawal_handlers;
