#!/bin/bash

echo " FidduPay Node SDK Publishing Script"
echo "======================================"
echo ""
echo " All checks passed:"
echo "   - 189 tests passing"
echo "   - Build successful"
echo "   - Package ready (24.9 kB)"
echo ""
echo " To publish, you need your 2FA code from your authenticator app"
echo ""
echo "Run this command with your 2FA code:"
echo "npm publish --otp=YOUR_6_DIGIT_CODE"
echo ""
echo "Example:"
echo "npm publish --otp=123456"
echo ""
echo " Package will be published to:"
echo "https://www.npmjs.com/package/@fiddupay/fiddupay-node"
